## Fundamental concept to get started with Tensorflow

Topics:
- `tf.constant` -> constant value
- `tf.variable` -> variable tenses

In [1]:
import tensorflow as tf
print(tf.__version__) # 2.18.0 in March 2025
# but our corse follows 2.3.0

2.18.0


### tf.constant

In [10]:
# https://www.tensorflow.org/api_docs/python/tf/constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# can converts any iterable into constant tensor
# it can also takes list or np.array and even list of list
vector = tf.constant([1, 2, 3, 4])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [8]:
vector[2]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [11]:
# check the number of dimention if any tensor
scalar.ndim, vector.ndim

(0, 1)

In [12]:
matrix = tf.constant([[1, 2],
                      [3, 4]])
matrix.ndim

2

In [13]:
matrix.dtype

tf.int32

In [14]:
another_matrix = tf.constant([
    [10., 7.],
    [6., 5],
    [4, 3]
])
another_matrix # note: dtype is set tobe float32

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 6.,  5.],
       [ 4.,  3.]], dtype=float32)>

In [17]:
# we can scafity the dtype at the time creation
another_matrix = tf.constant([
    [10.55, 7.],
    [6., 5],
    [4, 3]
], dtype=tf.int32) # Type error

TypeError: Cannot convert [[10.55, 7.0], [6.0, 5], [4, 3]] to EagerTensor of dtype int32

In [18]:
another_matrix = tf.constant([
    [10.55, 7.],
    [6., 5],
    [4, 3]
], dtype=tf.float16)
# 16bit precision.  the higher the number more preciously stored. but it also costs more memory

In [19]:
tensor = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
    ], dtype=tf.int16)
tensor.ndim
# no matter what we give vector, matrix, or a single value.
# everything in tensorflow is considered as Tensor
# just the ndim is varried.

3