In [2]:
import tensorflow as tf
import numpy as np

In [4]:
tensor = tf.constant(np.random.randint(0, 100, 25))
tensor

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([47, 58,  1, 75, 99, 34, 23,  4, 62, 43, 81, 73, 62, 38, 93, 71, 52,
       87, 11, 74, 44, 11, 56, 55, 41])>

In [6]:
tf.reduce_max(tensor) # 99

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [7]:
tf.reduce_min(tensor) # 1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [8]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1295>

In [9]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=51>