In [1]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [ ]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.uniform(shape=[50]), shape = [1, 1, 1, 1, 50])
tensor

In [7]:
" docs: Removes dimensions of size 1 from the shape of a tensor. "
tf.squeeze(tensor)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [11]:
tensor = tf.constant(tf.random.uniform(shape=[50]), shape = [1, 1, 25, 2, 1])
tensor

<tf.Tensor: shape=(1, 1, 25, 2, 1), dtype=float32, numpy=
array([[[[[0.7413678 ],
          [0.62854624]],

         [[0.01738465],
          [0.3431449 ]],

         [[0.51063764],
          [0.3777541 ]],

         [[0.07321596],
          [0.02137029]],

         [[0.2871771 ],
          [0.4710616 ]],

         [[0.6936141 ],
          [0.07321334]],

         [[0.93251204],
          [0.20843053]],

         [[0.70105827],
          [0.45856392]],

         [[0.8596262 ],
          [0.92934334]],

         [[0.20291913],
          [0.76865506]],

         [[0.60016024],
          [0.27039742]],

         [[0.88180614],
          [0.05365038]],

         [[0.42274463],
          [0.89037776]],

         [[0.7887033 ],
          [0.10165584]],

         [[0.19408834],
          [0.27896714]],

         [[0.39512634],
          [0.12235212]],

         [[0.38412368],
          [0.9455296 ]],

         [[0.77594674],
          [0.94442344]],

         [[0.04296565],
          [0.47460

In [12]:
tf.squeeze(tensor) # removes left 1 and right 1 from shape

<tf.Tensor: shape=(25, 2), dtype=float32, numpy=
array([[0.7413678 , 0.62854624],
       [0.01738465, 0.3431449 ],
       [0.51063764, 0.3777541 ],
       [0.07321596, 0.02137029],
       [0.2871771 , 0.4710616 ],
       [0.6936141 , 0.07321334],
       [0.93251204, 0.20843053],
       [0.70105827, 0.45856392],
       [0.8596262 , 0.92934334],
       [0.20291913, 0.76865506],
       [0.60016024, 0.27039742],
       [0.88180614, 0.05365038],
       [0.42274463, 0.89037776],
       [0.7887033 , 0.10165584],
       [0.19408834, 0.27896714],
       [0.39512634, 0.12235212],
       [0.38412368, 0.9455296 ],
       [0.77594674, 0.94442344],
       [0.04296565, 0.4746096 ],
       [0.6548251 , 0.5657116 ],
       [0.13858628, 0.3004663 ],
       [0.3311677 , 0.12907016],
       [0.6435652 , 0.45473957],
       [0.68881893, 0.30203617],
       [0.49152803, 0.26529062]], dtype=float32)>

In [13]:
tensor = tf.constant(tf.random.uniform(shape=[50]), shape = [1, 1, 25, 1, 2, 1])
tensor

<tf.Tensor: shape=(1, 1, 25, 1, 2, 1), dtype=float32, numpy=
array([[[[[[0.7402308 ],
           [0.33938193]]],


         [[[0.5692506 ],
           [0.44811392]]],


         [[[0.29285502],
           [0.4260056 ]]],


         [[[0.62890387],
           [0.691061  ]]],


         [[[0.30925727],
           [0.89236605]]],


         [[[0.66396606],
           [0.30541587]]],


         [[[0.8724164 ],
           [0.1025728 ]]],


         [[[0.56819403],
           [0.25427842]]],


         [[[0.7253866 ],
           [0.4770788 ]]],


         [[[0.46289814],
           [0.88944995]]],


         [[[0.6792555 ],
           [0.09752727]]],


         [[[0.01609659],
           [0.4876021 ]]],


         [[[0.5832968 ],
           [0.41212583]]],


         [[[0.731905  ],
           [0.93418944]]],


         [[[0.5298122 ],
           [0.9664817 ]]],


         [[[0.88391197],
           [0.10578597]]],


         [[[0.44439578],
           [0.7851516 ]]],


         [[[0.4733251

In [14]:
tf.squeeze(tensor) # can remove middle 1 as well

<tf.Tensor: shape=(25, 2), dtype=float32, numpy=
array([[0.7402308 , 0.33938193],
       [0.5692506 , 0.44811392],
       [0.29285502, 0.4260056 ],
       [0.62890387, 0.691061  ],
       [0.30925727, 0.89236605],
       [0.66396606, 0.30541587],
       [0.8724164 , 0.1025728 ],
       [0.56819403, 0.25427842],
       [0.7253866 , 0.4770788 ],
       [0.46289814, 0.88944995],
       [0.6792555 , 0.09752727],
       [0.01609659, 0.4876021 ],
       [0.5832968 , 0.41212583],
       [0.731905  , 0.93418944],
       [0.5298122 , 0.9664817 ],
       [0.88391197, 0.10578597],
       [0.44439578, 0.7851516 ],
       [0.47332513, 0.89893615],
       [0.04290593, 0.8717004 ],
       [0.6068529 , 0.12963045],
       [0.4527359 , 0.24573493],
       [0.34777248, 0.582147  ],
       [0.82298195, 0.82862926],
       [0.877372  , 0.5319803 ],
       [0.03594303, 0.03986669]], dtype=float32)>