In [ ]:
" one-hot encoding is numerical way of representing data"

In [1]:
import tensorflow as tf
tf.__version__

In [2]:
some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [5]:
tf.one_hot(some_list, 3, on_value="dog", off_value="cat")

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'dog', b'cat', b'cat'],
       [b'cat', b'dog', b'cat'],
       [b'cat', b'cat', b'dog'],
       [b'cat', b'cat', b'cat']], dtype=object)>

In [9]:
some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=2) # so depth is the maximum index-value

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [12]:
indices = [[0, 2], [1, 4]]
depth = 3
tf.one_hot(indices, depth)  # output: [2 x 2 x 3]
# [[[1.0, 0.0, 0.0],   # one_hot(0)
#   [0.0, 0.0, 1.0]],  # one_hot(2)
#  [[0.0, 1.0, 0.0],   # one_hot(1)
#   [0.0, 0.0, 0.0]]]  # one_hot(4) out of boundery

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [0., 0., 0.]]], dtype=float32)>