In [1]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [3]:
tensor = tf.range(1, 100, 3)
tensor

<tf.Tensor: shape=(33,), dtype=int32, numpy=
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97],
      dtype=int32)>

In [4]:
tf.square(tensor)

<tf.Tensor: shape=(33,), dtype=int32, numpy=
array([   1,   16,   49,  100,  169,  256,  361,  484,  625,  784,  961,
       1156, 1369, 1600, 1849, 2116, 2401, 2704, 3025, 3364, 3721, 4096,
       4489, 4900, 5329, 5776, 6241, 6724, 7225, 7744, 8281, 8836, 9409],
      dtype=int32)>

In [5]:
tf.sqrt(tensor) # error: if endresult is float. tensor must be in float as well

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [6]:
tf.sqrt(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(33,), dtype=float32, numpy=
array([1.       , 2.       , 2.6457512, 3.1622777, 3.6055512, 4.       ,
       4.358899 , 4.690416 , 5.       , 5.2915025, 5.5677643, 5.8309517,
       6.0827627, 6.3245554, 6.5574384, 6.78233  , 7.       , 7.2111025,
       7.4161983, 7.615773 , 7.81025  , 8.       , 8.185352 , 8.3666   ,
       8.5440035, 8.717798 , 8.888194 , 9.055386 , 9.219544 , 9.380832 ,
       9.539392 , 9.69536  , 9.848858 ], dtype=float32)>

In [9]:
# tf.log # asias is not defined
# tf.math.log(tensor) # same error here

tf.math.log(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(33,), dtype=float32, numpy=
array([0.       , 1.3862944, 1.9459102, 2.3025851, 2.5649493, 2.7725887,
       2.944439 , 3.0910425, 3.218876 , 3.3322046, 3.4339871, 3.5263605,
       3.610918 , 3.6888795, 3.7612002, 3.8286414, 3.8918204, 3.9512436,
       4.0073333, 4.060443 , 4.1108737, 4.158883 , 4.204693 , 4.248495 ,
       4.2904596, 4.3307333, 4.3694477, 4.406719 , 4.4426513, 4.477337 ,
       4.5108595, 4.543295 , 4.574711 ], dtype=float32)>

In [ ]:
"there is all kinds of math functions like sin, cos, pow, ceil, floor, exp, mod, sinh"