In [2]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.18.0'

In [4]:
# tensorflow has well bounding with numpy

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [5]:
# we can also pass tensor to numpy
n = np.array(J)
n, type(n)

(array([ 3.,  7., 10.]), numpy.ndarray)

In [7]:
# or use the numpy method
n = J.numpy()
n, type(n)

(array([ 3.,  7., 10.]), numpy.ndarray)

In [9]:
# NOTE: the default types of eaaach are slightly different
numpy_j = tf.constant(np.array([3., 4, 5, 6]))
tensor_j = tf.constant([3., 4, 5, 6])

numpy_j.dtype, tensor_j.dtype # numpy will be float64, and python list -> float32

(tf.float64, tf.float32)

to summerise:
- if we ever need function from numpy that is not defined in tensorflow
- we can quickly convert tensor with .numpy method
