In [2]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [4]:
# 1st paramiter to give any random function is generally `shape`
tf.random.normal(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.78605   ,  0.7337846 ],
       [ 0.91429746, -1.307173  ],
       [-0.01731198,  0.62122095]], dtype=float32)>

In [8]:
# using seed
rand_1 = tf.random.Generator.from_seed(1234)
rand_1.normal(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.9356609 ,  1.0854305 ],
       [-0.93788373, -0.5061547 ],
       [ 1.3169702 ,  0.7137579 ]], dtype=float32)>

In [9]:
rand_1.normal(shape = (3, 2))
# 2nd will be diff from 1st. but every 2nd call after seed will have the same output.

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.39647493,  0.83695656],
       [-0.30946946,  1.1206646 ],
       [ 1.008526  , -0.10185789]], dtype=float32)>

In [23]:
# uniform distribution is also available
rand_1.uniform(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.24654162, 0.54596007],
       [0.03914618, 0.13007796],
       [0.43204963, 0.7787502 ]], dtype=float32)>

### shuffle a tensor

In [10]:
tensor = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [11]:
tf.random.shuffle(tensor) # we can provide seed as paramiter

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

**NOTE:** Randomly shuffles a tensor along its `first` dimension only. [referance](https://www.tensorflow.org/api_docs/python/tf/random/shuffle)

In [21]:
tf.random.shuffle(tensor, seed=42) # we can provide seed as paramiter

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [22]:
# but the function seed is also affected by global seed value
tf.random.set_seed(123)
tf.random.shuffle(tensor, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

- with in_function seed -> the shuffel will be changed with each run. (fixed based on number of run)
- but if i realy need a fix shuffer i must use global seed