In [1]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [3]:
# creating a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = (2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [4]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [5]:
rank_4_tensor.ndim

4

In [13]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [8]:
2*3*4*5

120

In [6]:
rank_4_tensor.size # error

AttributeError: EagerTensor object has no attribute 'size'. 
        If you are looking for numpy-related methods, please run the following:
        tf.experimental.numpy.experimental_enable_numpy_behavior()
      

In [14]:
tf.size(rank_4_tensor).numpy()

np.int32(120)

In [15]:
def meta_data(tensor):
  print("Data Type: ", tensor.dtype)
  print("Dimention: ", tensor.ndim)
  print("Shape: ", tensor.shape)
  print("Total element: ", tf.size(tensor).numpy())

meta_data(rank_4_tensor)

Data Type:  <dtype: 'float32'>
Dimention:  4
Shape:  (2, 3, 4, 5)
Total element:  120
