In [2]:
import tensorflow as tf

In [5]:
tensor = tf.constant([[10, 7],
                      [3, 4]])

In [7]:
tensor + 10 # added to the each element

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [8]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [9]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [11]:
tensor // 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 3],
       [1, 2]], dtype=int32)>

In [12]:
# but of course the original tensor is not changed
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [13]:
# we can also use tensorflow function for the same purpose
tf.multiply(tensor, 10)
# again the original tensor is not changed

# actually tf.multiply is part of tf.math.multiply but aliased as tf.multiply
# ref: https://www.tensorflow.org/api_docs/python/tf/math/multiply

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>