## Improving a model


To improve our model, we alter almost every part of the 3 steps we went through before.

1. **Creating a model** - here you might want to add more layers, increase the number of hidden units (also called neurons) within each layer, change the activation functions of each layer.
2. **Compiling a model** - you might want to choose optimization function or perhaps change the **learning rate** of the optimization function.
3. **Fitting a model** - perhaps you could fit a model for more **epochs** (leave it training for longer) or on more data (give the model more examples to learn from).

In [1]:
import tensorflow as tf

In [29]:
X = tf.constant([-7, -4, -1, 2, 5, 8, 11, 14.0])
Y = tf.constant([3, 6, 9, 12, 15, 18, 21, 24.0])

X, Y

(<tf.Tensor: shape=(8,), dtype=float32, numpy=array([-7., -4., -1.,  2.,  5.,  8., 11., 14.], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.], dtype=float32)>)

### twicking epochs

In [ ]:
# initiate
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)
])

# compile
model.compile(loss = tf.keras.losses.mae,
              optimizer = tf.keras.optimizers.SGD(),
              metrics = ['mae'])


In [ ]:
model.fit(tf.expand_dims(X, axis=-1), Y, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 688ms/step - loss: 11.6238 - mae: 11.6238
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - loss: 11.4913 - mae: 11.4913
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 11.3588 - mae: 11.3588
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 11.2263 - mae: 11.2263
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 11.0938 - mae: 11.0938
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 10.9613 - mae: 10.9613
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 10.8288 - mae: 10.8288
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 10.6963 - mae: 10.6963
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 10.5638 - mae: 10.5638
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 10.4313 - mae: 10.4313
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 10.2988 - mae: 10.2988
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 10.1663 - mae: 10.1663
Epoch 13/100
1/1 ━━━━━━

In [ ]:
model.predict(tf.constant([17]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[29.58025]], dtype=float32)

In [ ]:
model.predict(tf.constant([27])) # although the previous one was quite close

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[46.490696]], dtype=float32)

In [ ]:
" what is happening our model overlooking our data. evnever any new int comes it is trying to relate back to the ints it have seen"

""" the real way we evaluate our model is not the loss presentage by trainning data
we test it upon the data it has never seen before
"""

### improve hidden layers

In [10]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(1)
])

model.compile(loss="mae",
              optimizer = tf.keras.optimizers.SGD(),
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), Y, epochs=100, verbose=0)

In [11]:
model.predict(tf.constant([17]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[29.00508]], dtype=float32)

In [12]:
model.predict(tf.constant([37]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[59.163734]], dtype=float32)

In [18]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation="relu"),
    tf.keras.layers.Dense(1)# commenting this -> results in error
])

model.compile(loss="mae",
              optimizer = tf.keras.optimizers.SGD(),
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), Y, epochs=100, verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 862ms/step - loss: 13.2074 - mae: 13.2074
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 12.7478 - mae: 12.7478
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 12.2893 - mae: 12.2893
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 11.8276 - mae: 11.8276
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 11.3647 - mae: 11.3647
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 10.8842 - mae: 10.8842
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 10.3846 - mae: 10.3846
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 9.8634 - mae: 9.8634
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.3149 - mae: 9.3149
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 8.7337 - mae: 8.7337
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 8.1192 - mae: 8.1192
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 7.4711 - mae: 7.4711
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━

In [19]:
model.predict(tf.constant([37]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[70.348335]], dtype=float32)

### Obtimiser

In [37]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1)
])

model.compile(loss = "mae",
              optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),# NOTE: learning rate is the most important hyper paramiter that we can change
              metrics=["mae"])

model.fit(tf.expand_dims(X, axis=-1), tf.expand_dims(Y, axis=-1), epochs=50)# what is happening with expand_dims y

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 14.1167 - mae: 14.1167
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 13.2779 - mae: 13.2779
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 12.4577 - mae: 12.4577
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 11.6624 - mae: 11.6624
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 10.8701 - mae: 10.8701
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 10.0768 - mae: 10.0768
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 9.2828 - mae: 9.2828
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 8.6134 - mae: 8.6134
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 7.9737 - mae: 7.9737
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 7.3004 - mae: 7.3004
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 6.5914 - mae: 6.5914
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5.8469 - mae: 5.8469
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step -

In [40]:
model.predict(tf.constant([37]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[60.057823]], dtype=float32)

In [39]:
model.predict(tf.constant([27]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[44.838596]], dtype=float32)

In [27]:
X

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([-7, -4, -1,  2,  5,  8, 11, 14], dtype=int32)>

In [38]:
# what's the case with known value
model.predict(tf.constant([14])) # predicting wrong even with known value !!!!

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step


array([[25.250475]], dtype=float32)

![various options you can use to improve a neural network model](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/02-improving-a-model-from-model-perspective.png)