In [1]:
import tensorflow as tf

In [3]:
X = tf.range(-100, 100, 4)
y = X + 10

X_test = X[40:]
y_test = y[40:]

In [7]:
y_test = tf.expand_dims(y_test, axis=-1)


In [2]:
y_pred = tf.constant([[ 71.3803  ],
       [ 76.07425 ],
       [ 80.7682  ],
       [ 85.462166],
       [ 90.15613 ],
       [ 94.85007 ],
       [ 99.54402 ],
       [104.23797 ],
       [108.93192 ],
       [113.625885]])

In [12]:
y_test, y_pred

(<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
 array([[ 70],
        [ 74],
        [ 78],
        [ 82],
        [ 86],
        [ 90],
        [ 94],
        [ 98],
        [102],
        [106]], dtype=int32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 71.3803  ],
        [ 76.07425 ],
        [ 80.7682  ],
        [ 85.462166],
        [ 90.15613 ],
        [ 94.85007 ],
        [ 99.54402 ],
        [104.23797 ],
        [108.93192 ],
        [113.625885]], dtype=float32)>)

In [13]:
tf.keras.losses.mae(y_test, y_pred)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.3803024, 2.0742493, 2.7682037, 3.4621658, 4.156128 , 4.850067 ,
       5.5440216, 6.2379684, 6.931923 , 7.625885 ], dtype=float32)>

In [15]:
tf.keras.losses.mae(tf.squeeze(y_test), tf.squeeze(y_pred))
# remember: we will spent most of time in reshaping the array to fit the function

<tf.Tensor: shape=(), dtype=float32, numpy=4.503091335296631>

In [17]:
y_test = tf.squeeze(y_test)
y_pred = tf.squeeze(y_pred)
tf.keras.losses.MSE(y_test, y_pred)
# MSE will be larger than MAE

<tf.Tensor: shape=(), dtype=float32, numpy=24.25079345703125>

In [ ]:
# quick functions for mae and mse
def mae(y_true, y_pred):
    return tf.keras.losses.mae(
      tf.squeeze(y_true),
      tf.squeeze(y_pred)
    )

def mse(y_true, y_pred):
    return tf.keras.losses.MSE(
      tf.squeeze(y_true),
      tf.squeeze(y_pred)
    )

In [ ]:
tf.keras.losses.Huber()

## Evaluating predictions

Alongisde visualizations, evaulation metrics are your alternative best option for evaluating your model.

Depending on the problem you're working on, different models have different evaluation metrics.

Two of the main metrics used for regression problems are:
* **Mean absolute error (MAE)** - the mean difference between each of the predictions.
* **Mean squared error (MSE)** - the squared mean difference between of the predictions (use if larger errors are more detrimental than smaller errors).

The lower each of these values, the better.

You can also use [`model.evaluate()`](https://www.tensorflow.org/api_docs/python/tf/keras/Model#evaluate) which will return the loss of the model as well as any metrics setup during the compile step.

In [ ]:
# Evaluate the model on the test set
model.evaluate(X_test, y_test)

In our case, since we used MAE for the loss function as well as MAE for the metrics, `model.evaulate()` returns them both.

TensorFlow also has built in functions for MSE and MAE.

For many evaluation functions, the premise is the same: compare predictions to the ground truth labels.